name: Setup GitHub Authentication
inputs:
  GIT_TOKEN_BASIC:
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment Variable
      run: export GITHUB_TOKEN="$GIT_TOKEN_BASIC"
      shell: bash
      env:
        GIT_TOKEN_BASIC: ${{ inputs.GIT_TOKEN_BASIC }}
